version: '3'
services:
  hadoop:
    image: "sequenceiq/spark"
    ports:
      - "50010:50010"
      - "50020:50020"
      - "50070:50070"
      - "50075:50075"
      - "50090:50090"
      - "8020:8020"
      - "9000:9000"
      - "10020:10020"
      - "19888:19888"
      - "8030:8030"
      - "8031:8031"
      - "8032:8032"
      - "8033:8033"
      - "8040:8040"
      - "8042:8042"
      - "8088:8088"
      - "49707:49707"
      - "2122:2122"
  kafka:
    image: "wurstmeister/kafka"
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
  spark:
    image: "gettyimages/spark"
    ports:
      - "8080:8080"
    depends_on:
      - hadoop
  zookeeper:
    image: "zookeeper"
    ports:
      - "2181:2181"
